spring:
  application:
    name: serviceuser
  config:
    import: optional:configserver:http://localhost:8080/
    name: serviceuser

  redis:
    host: localhost
    port: 9090

server:
  port: 8082
